#! /usr/bin/zsh

uze cgi --setup

cat <<.
HTTP/1.1 200 OK
Content-Type: text/html
Connection: Closed

.

pandoc -sthtml5 <<.

# hello ${Q[user]:=mec}

you found me now

* learn html
* learn shell
* and hack

.
