#! /usr/bin/zsh
uze page
pug <<.
| HTTP/1.0 ${CODE:-200 OK}
| Content-Type: ${TYPE:-text/html}
| Connection: Closed
|
|
doctype html
html
    head
        title this is how you can render html using pug
    body
        h1 you can access to query params
        pre.
            hello \${USER:=mec},
            tu m'as bien dit "\${Q[greetings]:=hello}" ?
        p will render
        code hello ${USER:=mec}, tu m'as bien dit  "${Q[greetings]:=hello}" ?
.
