#! /usr/bin/zsh

uze cgi

# TODO: handle multiple headers ?
my% HTTP_CODE=(
    OK     200
    ERROR  500
)

# TODO: handle multiple headers ?
xml/attr/parse () {
    local tag id
    my@ class
    my@ data
    sed 's/[.,\!]/\n&\n/g' <<< $1 | {
        read tag
        @- {
            case $it {
                (!) read id ;;
                (.) read it ; class+=$it ;;
                (,) read it ; data+=$it ;;
            }
        }
    }
    (( $#id ))    && tag+=" id=\"$id\""
    (( $#class )) && tag+=" class=\"$class\""
    (( $#data )) && {
        set -- data-$^data
        tag+=" $*"
    }
    print -n $tag
}

http/header () {
    local code=${(U)1?http error name (case insensitive)}
    shift
    say   "HTTP/1.1 ${HTTP_CODE[$code]} $code" \
        "Content-Type: ${as:-text/html}" \
        "$@" \
        "Connection: Closed" '' }

echo love &> err || {
    as=text/plain http/header error
    echo error
    cat err
    return
}

xml/tag/close () {
    print -n "</${TAGSTACK[-1]}>"
    TAGSTACK[-1]=()
}

xml/tag/open () {
    TAGSTACK+=$1
    print -n "<$1" ;
    shift
    case ${1:-} {
        ([,.!]*) xml/attr/parse $1 ; shift ;;
    }

    while ((#)) {
        case $1 {
            (-) shift ; print -n ">$*" ; return ;;
            (/) print -n "/>"  ; TAGSTACK[-1]=()  ; return ;;
            (*) print -n \ $1=\"$2\" ; shift 2 ;;
        }
    }
    print -n ">"
}

xml/decltag () {
    eval $1 '() {xml/tag/open '$1 '"$@"}'
}

@ (html div head title body h{1-6} ul li meta table ) xml/decltag $it
alias é=xml/tag/open
alias è=xml/tag/close

my@ TAGSTACK

http/header ok

print '<!doctype html>'
html -
    head -
        title - a;è
        meta name author content 'marc chantreux' /
    è
    body -
        h1 !pagetitle.large.fun - hello world ;è
        div .step.annee,x=100,y=1000
            ul
                li - this is a cool DSL ;è
                li - 'pug alike ?'      ;è
                li - no dynamic langage ;è
            è
        è
        table -
            getent passwd | sed '
                s,:x:,</td><td>,
                s,$,</td></tr>,
                s,^,<tr><td>,
                s,:,</td><td>,g
            '
        è
    è
è
