#! /usr/bin/zsh

uze cgi

@ (html div head title body h{1-6} ul li meta table ) xml/decltag $it
alias é=xml/tag/open
alias è=xml/tag/close

my@ TAGSTACK

http/header ok

print '<!doctype html>'
html -
    head -
        title - a;è
        meta name author content 'marc chantreux' /
    è
    body -
        h1 !pagetitle.large.fun - hello world ;è
        div .step.annee,x=100,y=1000
            ul
                li - this is a cool DSL ;è
                li - 'pug alike ?'      ;è
                li - no dynamic langage ;è
            è
        è
        table -
            getent passwd | sed '
                s,:x:,</td><td>,
                s,$,</td></tr>,
                s,^,<tr><td>,
                s,:,</td><td>,g
            '
        è
    è
è
